name: Go
on:
  pull_request:
    branches:
    - master
    - release-*
    - ipv6
  push:
    branches:
    - master
    - release-*
    - ipv6
jobs:

  test-unit:
    name: Unit test
    runs-on: [ubuntu-18.04]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check-out code
      uses: actions/checkout@v2

    - name: Run unit tests
      run: make test-unit

    - name: Code coverage
      run: |
        bash <(curl -s https://codecov.io/bash) -f .coverage/coverage-unit.txt -F unit-tests -n codecov-unit-test > report.txt

    - name: Comment Action
      uses: JungWinter/comment@v1.1.0
      with:
        # create|edit
        type: create
        # github token
        token: 8d6f8445fe8ed12c1ff47ed2f078c721b76bde40
        # comment body
        body: https://codecov.io/github/vmware-tanzu/antrea/commit/${{secrets.GITHUB_TOKEN}}

  golangci-lint:
    name: Golangci-lint
    strategy:
      matrix:
        platform: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check-out code
      uses: actions/checkout@v2
    - name: Run golangci-lint
      run: make golangci


  golangci-lint-netpol-tmp:
    name: Golangci-lint for netpol code
    runs-on: [ubuntu-18.04]
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check-out code
      uses: actions/checkout@v2
    - name: Run golangci-lint
      working-directory: hack/netpol
      run: make golangci


  bin:
    name: Build Antrea binaries
    runs-on: [ubuntu-18.04]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check-out code
      uses: actions/checkout@v2

    - name: Build Antrea binaries
      run: make bin

    - name: Build Antrea windows binaries
      run: make windows-bin

  antctl:
    name: Build antctl for macOS, Linux and Windows
    runs-on: [ubuntu-18.04]
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check-out code
        uses: actions/checkout@v2

      - name: Build antctl binaries
        run: make antctl


  codegen:
    name: Check code generation
    runs-on: [ubuntu-18.04]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check-out code
      uses: actions/checkout@v2

    - name: Check code generation
      run: ./ci/check-codegen.sh


  manifest:
    name: Check manifest
    runs-on: [ubuntu-18.04]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check-out code
      uses: actions/checkout@v2

    - name: Check manifest
      run: ./ci/check-manifest.sh


  tidy:
    name: Check go.mod tidy
    runs-on: [ubuntu-18.04]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check-out code
      uses: actions/checkout@v2

    - name: Check tidy
      run: make test-tidy

  verify-spelling:
    name: Verify common spelling mistakes
    runs-on: [ubuntu-18.04]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check-out code
      uses: actions/checkout@v2

    - name: Run verify scripts
      run: make verify-spelling
